### ISSUE TITLE
Django 1.11 support

### ISSUE THREAD

**Issue by apollodatasolutions** [jazzband/django-model-utils#275]
Does this work with Django 1.11 yet?  The docs say 1.10 but I see that some 1.11 work was done already.   Any pending issues (maybe we can help with a PR)?

**Comment by VLZH** [comment]
@apollodatasolutions
I have problems with 'InheritanceManager', because in django 1.11 have changed behavior of iteration by model's instances.

My solution:
overwrite _fetch_all to previous version, it is brutal, but for me enough

Sorry for my english)

**Comment by sam-mi** [comment]
I'm not sure whether this is a Django 1.11 thing or a model-utils thing but I have noticed that since upgrading to 1.11 filtering like `status__in=Model.STATUS` returns en empty QuerySet. For example:
`Ticket.objects.all().filter(status__in=list(Ticket.ACTIVE._db_values)) # ['new', 'active', 'accepted'] `
returns a filtered queryset as expected but
`Ticket.objects.all().filter(status__in=Ticket.ACTIVE) # Choices(('new', 'new', 'new'), ('active', 'active', 'active'), ('accepted', 'accepted', 'accepted')) `
returns and empty queryset. 

> using `list(Ticket.ACTIVE._db_values)` is a workaround but not ideal

Any idea why?

**Comment by djstein** [comment]
#237 is also breaking on 1.11

**Comment by zh-h** [comment]
Django 1.11
Python 3.5.3

Broken
```
    raise AttributeError('Can only be accessed via an instance.')
AttributeError: Can only be accessed via an instance.
```

**Comment by cromanstata** [comment]
I'm not sure if that's helpful but I managed to overcome this by removing "jsonfield" and installing"django-jsonfield" instead.

**Comment by utapyngo** [comment]
FieldTracker does not work with django-countries on Django 1.11: 
https://github.com/jazzband/django-model-utils/issues/278

**Comment by JonnyWaffles** [comment]
Django 1.11.3
Python 3.6

FieldTracker is not working on by abstract base model.

```
class BaseSection(models.Model):
    tracker = FieldTracker()
 
    class Meta:
        abstract = True


>>> from myapp.models import BaseSection
>>> BaseSection.tracker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'BaseSection' has no attribute 'tracker'
```

**Comment by muroshi** [comment]
When will you issue a version, which works with the current Django version 1.11? Are there any parts which I can use even though it's not recommended yet?

**Comment by webyneter** [comment]
Any news on that?

**Comment by realsby** [comment]
fu
