### ISSUE TITLE
FieldTracker does not work properly with queryset.only()

### ISSUE THREAD

**Issue by mark-mishyn** [jazzband/django-model-utils#470]
## Problem

After update from 4.0 to 4.1 queryset.only() does not work if model uses FieldTracker and **there is tracked ForeignKey.**

## Environment

- Django Model Utils version: 4.1.1
- Django version: 3.1.4
- Python version: 3.8.1

## Code examples
```
class City(models.Model):
    pass

class User(models.Model):
    username = models.CharField(max_length=255)
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True)
    email_tracker = FieldTracker(fields=['city'])

User.objects.only('username')
```
raises this error:

```
/lib/python3.8/site-packages/model_utils/tracker.py in set_saved_fields(self, fields)
    106             self.saved_data = self.current()
    107         else:
--> 108             self.saved_data.update(**self.current(fields=fields))
    109 
    110         # preventing mutable fields side effects

AttributeError: 'FieldInstanceTracker' object has no attribute 'saved_data'
```
Not sure why there is try to update tracker on queryset evaluation.

**Comment by hramezani** [comment]
I tried to reproduce the error with your given model and query. but I couldn't.

**Comment by mark-mishyn** [comment]
@hramezani aha, my mistake, I've tried again on a fresh project and found out that error happens only if there is **ForeignKey** in **FieldTracker**. I've updated code example in issue description.

**Comment by hramezani** [comment]
You can track the `city_id`. because `city` is a foreign key.
```python
email_tracker = FieldTracker(fields=['city_id'])
```

**Comment by mark-mishyn** [comment]
@hramezani Thank's a lot, that works fine!
