### ISSUE TITLE
Django 2.0 issue - _clone -> _chain

### ISSUE THREAD

**Issue by tony** [jazzband/django-model-utils#295]
python 3.6.3

django 2.0.0

django-model-utils 3.0.0

```
  File "/Users/me/.local/share/virtualenvs/develtech-oQr_FNyw/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/me/.local/share/virtualenvs/develtech-oQr_FNyw/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/me/.local/share/virtualenvs/develtech-oQr_FNyw/lib/python3.6/site-packages/django/core/handlers/base.py", line 119, in _get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/Users/me/.local/share/virtualenvs/develtech-oQr_FNyw/lib/python3.6/site-packages/debug_toolbar/middleware.py", line 90, in process_view
    response = panel.process_view(request, view_func, view_args, view_kwargs)
  File "/Users/me/.local/share/virtualenvs/develtech-oQr_FNyw/lib/python3.6/site-packages/debug_toolbar_line_profiler/panel.py", line 200, in process_view
    out = self.profiler.runcall(view_func, *args, **view_kwargs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cProfile.py", line 109, in runcall
    return func(*args, **kw)
  File "/Users/me/.local/share/virtualenvs/develtech-oQr_FNyw/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/me/.local/share/virtualenvs/develtech-oQr_FNyw/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/me/.local/share/virtualenvs/develtech-oQr_FNyw/lib/python3.6/site-packages/django/views/generic/list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "/Users/me/work/develtech/based/app/posts/views/list.py", line 47, in get_queryset
    return self.filter.qs.select_subclasses().all()
  File "/Users/me/.local/share/virtualenvs/develtech-oQr_FNyw/lib/python3.6/site-packages/django/db/models/query.py", line 829, in all
    return self._chain()
  File "/Users/me/.local/share/virtualenvs/develtech-oQr_FNyw/lib/python3.6/site-packages/django/db/models/query.py", line 1156, in _chain
    obj = self._clone()
  File "/Users/me/.local/share/virtualenvs/develtech-oQr_FNyw/lib/python3.6/site-packages/model_utils/managers.py", line 100, in _clone
    return super(InheritanceQuerySetMixin, self)._clone(**kwargs)
TypeError: _clone() got an unexpected keyword argument 'subclasses'
```

**Comment by pincoin** [comment]
Hello,

I also encountered the same error, and I also changed `_clone` to `_chain`.

It works with Django 2.0, but it won't be compatible with Django 1.x.

```
    def _chain(self, klass=None, setup=False, **kwargs):
        for name in ['subclasses', '_annotated']:
            if hasattr(self, name):
                kwargs[name] = getattr(self, name)
        if django.VERSION < (1, 9):
            kwargs['klass'] = klass
            kwargs['setup'] = setup
        return super(InheritanceQuerySetMixin, self)._chain(**kwargs)
```

I am also looking forward to contributers' nicer patch.

**Comment by tony** [comment]
@pincoin yep, in #297 I did a07140e. I merged it into master. I'm going to get stuff updated in preparation for release.

**Comment by tony** [comment]
Fixed in @297
