### ISSUE TITLE
AttributeError: 'CountryDescriptor' object has no attribute 'field_name'

### ISSUE THREAD

**Issue by utapyngo** [jazzband/django-model-utils#278]
## Problem

When a `CountryField` is used as a deferred field, `FieldTracker` breaks at the following line:

                    field_tracker = DeferredAttributeTracker(
                        field_obj.field_name, None)

## Environment

- Django Model Utils version: 3.0.0
- Django version: 1.11.2
- Python version: 3.5.2
- Django Countries version: 4.6.1

## Code examples

models.py
```
from django.db import models
from django_countries.fields import CountryField
from model_utils import FieldTracker


class Location(models.Model):
    country = CountryField(blank=True)

    tracker = FieldTracker()
```

The following code fails on Django 1.11 but works on Django 1.9:
```
Location.objects.create()
print(list(Location.objects.only('id')))
```

Here is a test project with a single test that fails:
[django_model_utils_countries_tracker_test.zip](https://github.com/jazzband/django-model-utils/files/1097279/django_model_utils_countries_tracker_test.zip)
