### ISSUE TITLE
InheritanceManager does not work with Django 4.2.x in 4.3.1 

### ISSUE THREAD

**Issue by bmihelac** [jazzband/django-model-utils#587]
## Problem

In latest published version (4.3.1) `InheritanceManager` does not work with Django 4.2.x 

## Environment

- Django Model Utils version:
4.3.1

- Django version: 

4.2.9

- Python version: 

Python 3.8.5

- Other libraries used, if any:

## Code examples

Give code example that demonstrates the issue, or even better, write new tests that fails because of that issue.

```python
MyModel.objects.select_subclasses()
```

Raises `TypeError: _chain() got an unexpected keyword argument 'subclasses'`.

This does not occur when installed from `master` branch. It would be nice to publish new release.

**Comment by foarsitter** [comment]
@bmihelac does v4.4.0 solve your problems?

**Comment by bmihelac** [comment]
I just verified and can confirm that  there is no issue with `InheritanceManager` v4.4.0
